### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'return_state')

### ISSUE THREAD

**Issue by mrlzla** [titu1994/keras-SRU#2]
There is an error occured when run imdb_sru.py:
```
Traceback (most recent call last):
  File "imdb_sru.py", line 47, in <module>
    return_state=True)(prev_input)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/vladik/ml/keras-SRU/sru.py", line 93, in __init__
    super(SRU, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 181, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 277, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'return_state')
```
It seems that you forget to add param return_state to constructor of SRU

**Comment by titu1994** [comment]
`return_state` is a parameter inherited from Recurrent class, it doesnt have to be added as a parameter. What version of Keras are you using? Try it out with Keras 2.0.8

**Comment by mrlzla** [comment]
Thanks! It helps.
